const SLASH = '/';
const PARENT_FOLDER = '..';
const SLING_CONTENT = 'SLING-CONTENT';
const PEREGRINE_SOURCE_ROOT = PARENT_FOLDER + SLASH + 'peregrine-cms';
const OUTPUT_ROOT = PARENT_FOLDER + SLASH + 'peregrine-converted-to-sling12';
const CONTENT_XML = '.content.xml';

module.exports = {
    SLASH: SLASH,
    SLING_CONTENT: SLING_CONTENT,
    PEREGRINE_SOURCE_ROOT: PEREGRINE_SOURCE_ROOT,
    OUTPUT_ROOT: OUTPUT_ROOT,
    CONTENT_XML: CONTENT_XML
}